### ISSUE TITLE
building `xintegration`

### ISSUE THREAD

**Issue by idkjs** [StrongerXi/Fish#4]
How do you build `xintegration`?

I have forked the project and changed the syntax and want to run it against `server.re` rather than `server.ml`.

Thanks for sharing your project.

**Comment by StrongerXi** [comment]
I assume you meant `xserver.ml`?

Basically `xintegration` is a script that can be used to run different binary for integration tests (whose source files are in `src/test/integration`). The essence of `xintegration` is this:
```bash
dune exec $SOURCE_WITHOUT_SUFFIX.exe 
```
i.e., it delegates to `dune` for (a) building the binary and (b) executing it.

I'm not familiar enough with the build system for ReScript, but if you wish to run `src/test/integration/xserver.re`, just find a way to build the ReScript project with `xserver.re` as the entry code.

Hope this helps:).

**Comment by idkjs** [comment]
Great! I will try it. Its not Rescript. Its Reason, which is OCaml. So should not be any different. The build binary `xintegration` in the project is expecting a `.ml` file so using your alternate instruction should do the trick. Thanks for taking the time. Best to you.
